name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]  # updates every hour
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories, activity, community
          config_timezone: Asia/Kolkata
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_threshold: 2%
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
